# Generated by Django 3.1.4 on 2021-02-07 13:22

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0021_site_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('color', models.CharField(default='#e60044', max_length=120)),
                ('sorting', models.IntegerField(default=0)),
                ('user_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_user_sites', to='account.usersite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
                ('whatsapp_message', models.TextField(blank=True, max_length=320)),
                ('price', models.CharField(blank=True, default='', max_length=120)),
                ('new_price', models.CharField(blank=True, default='', max_length=120)),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construct_site_food.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=40)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/')),
                ('value', models.TextField(blank=True, null=True)),
                ('user_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_data_user_sites', to='account.usersite')),
            ],
        ),
    ]
