# Generated by Django 3.1.4 on 2021-02-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_site_slug'),
        ('construct_site_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='user_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_categories', to='account.usersite'),
        ),
    ]
