# Generated by Django 3.1.4 on 2021-02-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0002_good_user_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalData',
        ),
    ]
