# Generated by Django 3.1.4 on 2021-02-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0004_good_sorting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='whatsapp_message',
        ),
    ]
