# Generated by Django 3.1.4 on 2021-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0006_auto_20210208_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
