# Generated by Django 3.1.4 on 2021-02-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0007_good_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='description',
        ),
    ]
