# Generated by Django 3.1.4 on 2021-02-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210207_2030'),
        ('construct_site_food', '0008_remove_good_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='user_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_user_sites', to='account.usersite'),
        ),
    ]
