# Generated by Django 3.1.4 on 2021-02-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0009_auto_20210208_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
