# Generated by Django 3.1.4 on 2021-03-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0012_good_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_slider',
        ),
    ]
