# Generated by Django 3.1.4 on 2021-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site_food', '0013_auto_20210301_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#fc8019', max_length=120),
        ),
    ]
