# Generated by Django 3.1.4 on 2021-01-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usersite_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Написать по ватсапу', max_length=80)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=18)),
                ('whatsapp_text', models.CharField(max_length=120)),
            ],
        ),
    ]
