# Generated by Django 3.1.4 on 2021-01-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='slug',
        ),
        migrations.AddField(
            model_name='support',
            name='user_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.usersite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='whatsapp_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
