# Generated by Django 3.1.4 on 2021-01-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210108_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
