# Generated by Django 3.1.4 on 2021-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_support_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='company_name',
            field=models.CharField(default='gosite', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersite',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
