# Generated by Django 3.1.4 on 2021-01-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210113_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersite',
            old_name='company_name',
            new_name='icon_text',
        ),
    ]
