# Generated by Django 3.1.4 on 2021-01-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210113_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersite',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='usersite',
            name='icon_text',
        ),
    ]
