# Generated by Django 3.1.4 on 2021-01-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210113_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=18)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.support')),
            ],
        ),
    ]
