# Generated by Django 3.1.4 on 2021-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210119_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
