# Generated by Django 3.1.4 on 2021-01-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_phonenumber_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='is_active',
        ),
    ]
