# Generated by Django 3.1.4 on 2021-01-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_currentsupportphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsupportphonenumber',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.phonenumber'),
        ),
        migrations.AlterField(
            model_name='currentsupportphonenumber',
            name='support',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.support'),
        ),
    ]
