# Generated by Django 3.1.4 on 2021-01-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210121_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentSupportPhoneNumber',
        ),
    ]
