# Generated by Django 3.1.4 on 2021-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210129_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(default='default', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
