# Generated by Django 3.1.4 on 2021-02-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_site_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user_site',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
