# Generated by Django 3.1.4 on 2021-02-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210207_2030'),
        ('construct_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Написать по ватсапу', max_length=80)),
                ('bacground_color', models.CharField(default='#25d366', max_length=120)),
                ('text_color', models.CharField(default='#ffffff', max_length=120)),
                ('icon_color', models.CharField(default='#ffffff', max_length=120)),
                ('whatsapp_text', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('user_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usersite')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construct_site.support')),
            ],
        ),
    ]
