# Generated by Django 3.1.4 on 2021-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site', '0006_auto_20210219_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=380)),
                ('description', models.TextField()),
            ],
        ),
    ]
