# Generated by Django 3.1.4 on 2021-02-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210207_2030'),
        ('construct_site', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='user_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.usersite'),
            preserve_default=False,
        ),
    ]
