# Generated by Django 3.1.4 on 2021-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct_site', '0008_faq_user_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='sorting',
            field=models.IntegerField(default=0),
        ),
    ]
